# pull official base image
FROM node:16.3.0-alpine AS prod

ARG REACT_APP_ENV
ARG REACT_APP_BASE_URL
ARG REACT_APP_BACKEND_URL

WORKDIR /app

COPY package.json /app

RUN npm install

COPY . /app

ENV REACT_APP_ENV=${REACT_APP_ENV}
ENV REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

RUN npm run build

FROM nginx:alpine

# Copy config nginx
COPY --from=prod /app/proxy/nginx.dev.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static assets from builder stage
COPY --from=prod /app/build .

EXPOSE 80

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
